const lineToKey = {
    1 : 'name',
    2 : 'data.details.type',
    3 : 'data.traits.size',
    4 : 'data.attributes.ac.value',
    5 : 'data.attributes.hp.value',
    6 : 'data.attributes.hp.max',
    7 : 'data.attributes.hp.formula',
    8 : 'data.attributes.speed',
    9 : 'data.traits.sesnses',
    10 : 'data.details.alignment',
    11 : 'data.details.cr',
    12 : 'data.details.xp.value',
    13 : 'data.abilities.str.value',
    14 : 'data.abilities.dex.value',
    15 : 'data.abilities.con.value',
    16 : 'data.abilities.int.value',
    17 : 'data.abilities.wis.value',
}

const attrToWordIndex = {
    'name' : [0,[0]],
    'size' : [1,[0]],
    'type' : [1,[1]],
    'alignment' : [0,[2,3]],
    'ac' : [2,[2]],
    'hp' : [3,[2]],
    'hpFormula' : [3,[3,4,5]],
    'speed' : [4,[1]],
    'str' : [6,[0]],
    'dex' : [8,[0]],
    'con' : [10,[0]],
    'int' : [12,[0]],
    'wis' : [14,[0]],
    'cha' : [16,[0]],
}

const skillsMap = {
    'Acrobatics' : 'acr',
    'Animal Handling' : 'ani',
    'Arcana' : 'arc',
    'Athletics' : 'ath',
    'Deception' : 'dec',
    'History' : 'his',
    'Insight' : 'ins',
    'Intimidation' : 'itm',
    'Investigation' : 'inv',
    'Medicine' : 'med',
    'Nature' : 'nat',
    'Perception' : 'prc',
    'Performance' : 'prf',
    'Persuasion' : 'per',
    'Religion' : 'rel',
    'Sleight of Hand' : 'slt',
    'Stealth' : 'ste',
    'Survival ' : 'sur',
}

// const lineToAttributeName = {
//     'name' : 'name',
//     'type' : 'data.details.type',
//     'size' : 'data.traits.size',
//     'ac' : 'data.attributes.ac.value',
//     'hp' : 'data.attributes.hp.value',
//     'hp' : 'data.attributes.hp.max',
//     'hd' : 'data.attributes.hp.formula',
//     'speed' : 'data.attributes.speed',
//     'senses' : 'data.traits.sesnses',
//     'alignment' : 'data.details.alignment',
//     'cr' : 'data.details.cr',
//     'xp' : 'data.details.xp.value',
//     'str' : 'data.abilities.str.value',
//     'dex' : 'data.abilities.dex.value',
//     'con' : 'data.abilities.con.value',
//     'int' : 'data.abilities.int.value',
//     'wis' : 'data.abilities.wis.value',
//     'cha' : 'data.abilities.cha.value',
// }

