const lineToKey = {
    2 : 'details.type',
    3 : 'traits.size',
    4 : 'attributes.ac.value',
    5 : 'attributes.hp.value',
    6 : 'attributes.hp.max',
    7 : 'attributes.hp.formula',
    8 : 'attributes.speed',
    9 : 'traits.sesnses',
    10 : 'details.alignment',
    11 : 'details.cr',
    12 : 'details.xp.value',
    13 : 'abilities.str.value',
    14 : 'abilities.dex.value',
    15 : 'abilities.con.value',
    16 : 'abilities.int.value',
    17 : 'abilities.wis.value',
}

const attrToWordIndex = {
    'name' : [0,[0]],
    'size' : [1,[0]],
    'type' : [1,[1]],
    'alignment' : [0,[2,3]],
    'ac' : [2,[2]],
    'hpval' : [3,[2]],
    'hpmax' : [3,[2]],
    'hpformula' : [3,[3,4,5]],
    'speed' : [4,[1]],
    'str' : [6,[0]],
    'dex' : [8,[0]],
    'con' : [10,[0]],
    'int' : [12,[0]],
    'wis' : [14,[0]],
    'cha' : [16,[0]],
}

const skillsMap = {
    'Acrobatics' : 'acr',
    'Animal Handling' : 'ani',
    'Arcana' : 'arc',
    'Athletics' : 'ath',
    'Deception' : 'dec',
    'History' : 'his',
    'Insight' : 'ins',
    'Intimidation' : 'itm',
    'Investigation' : 'inv',
    'Medicine' : 'med',
    'Nature' : 'nat',
    'Perception' : 'prc',
    'Performance' : 'prf',
    'Persuasion' : 'per',
    'Religion' : 'rel',
    'Sleight of Hand' : 'slt',
    'Stealth' : 'ste',
    'Survival ' : 'sur',
}

const attributeToKey = {
    // 'name' : 'name',
    'size' : 'traits.size',
    'type' : 'details.type',
    'alignment' : 'details.alignment',
    'ac' : 'attributes.ac.value',
    'hpval' : 'attributes.hp.value',
    'hpmax' : 'attributes.hp.max',
    'hpformula' : 'attributes.hp.formula',
    'speed' : 'attributes.speed',
    'str' : 'abilities.str.value',
    'dex' : 'abilities.dex.value',
    'con' : 'abilities.con.value',
    'int' : 'abilities.int.value',
    'wis' : 'abilities.wis.value',
    'cha' : 'abilities.cha.value',
}

